version: '3.8'

services:
  front:
    container_name: front
    build: ./front
    volumes:
      - ".:./app/src"
    ports:
      - 3000:3000

  back:
    container_name: back
    build: ./back
    volumes:
      - ".:./app/src"
    ports:
      - 3001:3001

  oauth2-proxy:
      image: bitnami/oauth2-proxy:7.3.0
      command: --config /oauth2.cfg
      volumes:
        - "./oauth2.cfg:/oauth2.cfg"
      ports:
        - 4180:4180 
