version: '3.8'

services:
  app:
    container_name: web_app
    image: web_app
    build: ./
    volumes:
      - "./src:/app/src"
    ports:
      - 3000:3000

  oauth2-proxy:
      image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
      command: --config /oauth2.cfg
      volumes:
        - ./oauth2.cfg:/oauth2.cfg
      ports:
        - 4180:4180 
